#!/usr/bin/env python3

from irrigation.dbus_interfaces import DBusIrrigationSystem, DBusIrrigator

import sdbus
import asyncio


irrigation_system = DBusIrrigationSystem.new_proxy(
    bus = sdbus.sd_bus_open_user(),
    service_name = 'me.faschingbauer.IrrigationService',
    object_path = '/me/faschingbauer/IrrigationSystem')
